<?php echo $this->include('email/email_header') ?>           
<!-- START CENTERED WHITE CONTAINER -->
<table role="presentation" class="main">
	<!-- START MAIN CONTENT AREA -->
	<tr>
		<td class="wrapper">
			<table role="presentation" border="0" cellpadding="0" cellspacing="0" style="padding-bottom:20px;">
				<tr>										<td><img src="<?php echo base_url()."/assets/img/welcome.jpg"; ?>" alt="" width="100%" style="display: block;" /></td>				</tr>				<tr>					<td style="padding: 20px 0px; line-height: 20px;">						<p style="color: #000000;font-size:11px; margin-bottom: 0px;">Welcome to <a href="<?php echo base_url(); ?>">planebroker.com</a> the premier platform for showcasing pet grooming excellence!</p>						<p style="color: #555555;font-size:11px; margin-bottom: 5px;">We're delighted to welcome you to our community of dedicated plane brokers who are committed to delivering exceptional services for our beloved furry companions. To begin, kindly log in to your dashboard and finalize your profile. If you have any inquiries or concerns, please reach out to our support team for assistance.</p>						<p style=" text-align: center; margin: 20px 0px;">							<a href="<?php echo base_url(); ?>/providerauth/login" style='display: inline-block; line-height: 14px; font-size: 12px;font-weight: 700;text-decoration: none;padding: 12px 50px;background-color: #ff6c00; color: #ffffff !important;border-radius: 25px; letter-spacing: 1px;'>LOG IN NOW</a>						</p>					</td>				</tr>				<tr>					<td style="padding: 30px 0 0; border-top: 1px solid #d2d2d2; text-align: center;">						<h3 style="font-size:20px; font-weight: 900;margin-bottom: 0;">Important Steps to Get Started!</h3>					</td>				</tr>				<tr>					<td>						<table border="0" cellpadding="0" cellspacing="0" style="padding: 40px 0; border-bottom: 1px solid #d2d2d2;">							<tr>								<td width="30%" style="padding-right:30px;"><img src="<?php echo base_url()."/assets/img/photo.png"; ?>" alt="" style="display: block;"/></td>								<td>									<p style="font-size: 11px;line-height: 20px;">It’s important for potential customers to see a complete profile!  Make sure to add your profile photo and additional photos of your work. You can add Tags to your photos so that customers can filter your gallery with ease. </p>									<a href="<?php echo base_url(); ?>/providerauth/photos" style='display: inline-block; line-height: 14px; font-size: 12px;font-weight: 400;text-decoration: none;padding: 12px 50px;background-color: #000000; color: #ffffff;border-radius: 15px;'>Edit My Photos</a>								</td>							</tr>						</table>						<table border="0" cellpadding="0" cellspacing="0" style="padding: 40px 0; border-bottom: 1px solid #d2d2d2;">							<tr>								<td width="30%" style="padding-right:30px;" align="center"><img src="<?php echo base_url()."/assets/img/useredit.png"; ?>" alt="" style="display: block;"/></td>								<td>									<p style="font-size: 11px;line-height: 20px;">Finalize your profile by adding your hours of operations and rates.  Make sure to review all your details to make sure your potential customers are viewing the correct information from your profile. </p>
				<?php $busine_name = !empty($business_name) ? $business_name : $fullname ; ?>
				<a href="<?php echo base_url(); ?>/providerauth/edit-profile" style='display: inline-block; line-height: 14px; font-size: 12px;font-weight: 400;text-decoration: none;padding: 12px 50px;background-color: #000000; color: #ffffff;border-radius: 15px;'>Edit My Profile</a>								</td>							</tr>						</table>						<table border="0" cellpadding="0" cellspacing="0" style="padding: 40px 0; border-bottom: 1px solid #d2d2d2;">							<tr>								<td width="30%" style="padding-right:30px;" align="center"><img src="<?php echo base_url()."/assets/img/upload.png"; ?>" alt="" style="display: block;"/></td>								<td>									<p style="font-size: 11px;line-height: 20px;">Share your profile! <a href="<?php echo base_url(); ?>">planebroker.com</a> provides you with a unique profile that allows you to share with your current and potential customers.  This serves as your own personal web page and one you should be product to share!</p>									<a href="
<?php echo base_url('provider/'.cleanURL(strtolower(str_replace(' ','-',$busine_name))).'/'.base64_encode($id)); ?>" style='display: inline-block; line-height: 14px; font-size: 12px;font-weight: 400;text-decoration: none;padding: 12px 50px;background-color: #000000; color: #ffffff;border-radius: 15px;'>Share Profile</a>								</td>							</tr>						</table>					</td>				</tr>
			</table>
		</td>
	</tr>
	<!-- END MAIN CONTENT AREA -->
</table>
<?php echo $this->include('email/email_footer') ?>
